master:
  extraFlags:
  - --maxmemory 8gb
  - --maxmemory-policy volatile-ttl
  nodeSelector:
    eks.amazonaws.com/nodegroup: cbioportal-hackathon
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cbioportal-hackathon"
      effect: "NoSchedule"
  persistence:
    enabled: false
replica:
  extraFlags:
  - --maxmemory 8gb
  - --maxmemory-policy volatile-ttl
  nodeSelector:
    eks.amazonaws.com/nodegroup: cbioportal-hackathon
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cbioportal-hackathon"
      effect: "NoSchedule"
  persistence:
    enabled: false
